kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/guimou/ocs-photo-album.git'
  name: ocs-photo-album-git
  labels:
    app: ocs-photo-album-git
    app.kubernetes.io/component: ocs-photo-album-git
    app.kubernetes.io/instance: ocs-photo-album-git
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: ocs-photo-album
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 12-ubi8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ocs-photo-album-git:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:12-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/guimou/ocs-photo-album.git'
    contextDir: /
  triggers:
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial
